### ISSUE TITLE
Numbering

### ISSUE THREAD

**Issue by CDinSV** [JoshuaCarroll/BasketballRosterManager#36]
Is there a way to have it go numerically and not a 1, 10, 11, 2, 22, 24, 4, 42 5, 55 order?

**Comment by JoshuaCarroll** [comment]
Yes, since it is possible that players might be wearing 00 and 0 on the same team, I had to store the jersey numbers as a string.  Really what this means is that you'll need to enter the jersey numbers as:

01, 10, 11, 02, 22, 24, 04, 42, 05, and 55.  

When you do that, they will appear in numeric order.  I'll think about how I can make that requirement more obvious.
